Use scratch as base image
rancher/image-build-crictl pull request #28
Opened 2024-05-13 10:58 UTC by manuelbuil

2024-05-13 16:14 UTC, dereknola requested changes

2024-05-13 16:14 UTC, dereknola commented on Dockerfile
> -ARG BCI_IMAGE=registry.suse.com/bci/bci-base
You removed the line that provides BCI_IMAGE?

2024-05-13 16:15 UTC, dereknola approved these changes

2024-05-14 08:37 UTC, rbrtbnfgl approved these changes

2024-05-14 08:38 UTC, cwayne18 approved these changes

2024-05-14 08:40 UTC, merged